//created on: Jan 27, 2013
package com.zenred.cosmos.service


//list any import classes here.
import com.zenred.service.GenerateAtmosphere;
import com.zenred.cosmos.DrawRolls;

//declare any global variables here




rule "StarColorStrictPass"
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
    	$drawRolls : DrawRolls()
        //conditions  1-6 strict, 7-9 flex, 10 goofy
        DrawRolls(eval($drawRolls.Instance().get_D10() < 6))
    then
        //actions
        $generateAtmosphere.strictDraw($generateAtmosphere.getAtmosphereProfileMap($generateAtmosphere.getColorType()))

end

rule "StarColorFlexPass"
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
    	$drawRolls : DrawRolls()
        //conditions  1-6 strict, 7-9 flex, 10 goofy
        DrawRolls(eval($drawRolls.Instance().get_D10() > 5))
    then
        //actions
        $generateAtmosphere.flexDraw($generateAtmosphere.getAtmosphereProfileMap($generateAtmosphere.getColorType()))

end

rule "StarColorGoofyPass"
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
    	$drawRolls : DrawRolls()
        //conditions  1-6 strict, 7-9 flex, 10 goofy
        DrawRolls(eval($drawRolls.Instance().get_D10() > 9))
    then
        //actions
        $generateAtmosphere.goofyDraw($generateAtmosphere.getAtmosphereProfileMap($generateAtmosphere.getColorType()))

end
