//created on: Jan 27, 2013
package com.zenred.cosmos.service



//list any import classes here.
import com.zenred.service.GenerateAtmosphere;


//declare any global variables here



rule "StarColorStrictPass"
	salience 10
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        //conditions  1-6 strict, 7-9 flex, 10 goofy
        GenerateAtmosphere(eval($generateAtmosphere.drawRandom10() < 6))
    then
        //actions
        $generateAtmosphere.strictDraw($generateAtmosphere.getAtmosphereProfileMap($generateAtmosphere.getColorType()))

end

rule "StarColorFlexPass"
	salience 20
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        //conditions  1-6 strict, 7-9 flex, 10 goofy
        GenerateAtmosphere(eval($generateAtmosphere.drawRandom10() > 5))
    then
        //actions
        $generateAtmosphere.flexDraw($generateAtmosphere.getAtmosphereProfileMap($generateAtmosphere.getColorType()))

end

rule "StarColorGoofyPass"
	salience 30
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
       //conditions  1-6 strict, 7-9 flex, 10 goofy
        GenerateAtmosphere(eval($generateAtmosphere.drawRandom10() > 9))
    then
        //actions
        $generateAtmosphere.goofyDraw($generateAtmosphere.getAtmosphereProfileMap($generateAtmosphere.getColorType()))

end
