//created on: Jan 27, 2013
package com.zenred.cosmos.service



//list any import classes here.
import com.zenred.service.GenerateAtmosphere;


//declare any global variables here

rule "strict_only"
	salience 5
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        // default action if no draws
        GenerateAtmosphere(eval($generateAtmosphere.isStrictOnly))
    then
        //actions
        $generateAtmosphere.setStrongUV(275.0);
        $generateAtmosphere.genStrictOnly();
end

rule "strict_and_flexible"
	salience 5
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        // default action if no draws
        GenerateAtmosphere(eval($generateAtmosphere.isStrictAndFlexible))
    then
        //actions
        $generateAtmosphere.genStrictAndFlexible();
end

rule "strict_and_goofy"
	salience 5
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        // default action if no draws
        GenerateAtmosphere(eval($generateAtmosphere.isStrictAndGoofy))
    then
        //actions
        $generateAtmosphere.genStrictAndGoofy();
end

rule "all_possible"
	salience 5
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        // default action if no draws
        GenerateAtmosphere(eval($generateAtmosphere.isAllPossible))
    then
        //actions
        $generateAtmosphere.genAllPossible();
end

rule "felxible_and_goofy"
	salience 5
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        // default action if no draws
        GenerateAtmosphere(eval($generateAtmosphere.isFlexibleAndGoofy))
    then
        //actions
        $generateAtmosphere.genFlexibleAndGoofy();
end

rule "felxible_only"
	salience 5
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        // default action if no draws
        GenerateAtmosphere(eval($generateAtmosphere.isFlexibleOnly))
    then
        //actions
        $generateAtmosphere.genFlexibleOnly();
end

rule "goofy_only"
	salience 5
	dialect "mvel"
    when $generateAtmosphere : GenerateAtmosphere()
        // default action if no draws
        GenerateAtmosphere(eval($generateAtmosphere.isGoofyOnly))
    then
        //actions
        $generateAtmosphere.genGoofyOnly();
end
