/*
 * ClassName.java
 *
 * Created on April 7, 2001, 9:07 PM
 */

package com.zenred.cosmos;

/**
 *
 * @author  jredden
 * @version 
 */
public class Builder extends javax.swing.JApplet {

    /** Creates new form ClassName */
    public Builder() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        jMenuBar1 = new javax.swing.JMenuBar ();
        jMenu1 = new javax.swing.JMenu ();
        jTextPane1 = new javax.swing.JTextPane ();
        jTextArea1 = new javax.swing.JTextArea ();
        jMenuBar1.setBackground (java.awt.Color.darkGray);
        jMenuBar1.setForeground (java.awt.Color.green);

          jMenu1.setText ("Menu");
  
          jMenuBar1.add (jMenu1);



        getContentPane ().add (jTextPane1, java.awt.BorderLayout.EAST);

        jTextArea1.setBackground (java.awt.Color.lightGray);
        jTextArea1.setForeground (java.awt.Color.green);


        getContentPane ().add (jTextArea1, java.awt.BorderLayout.EAST);

        setJMenuBar (jMenuBar1);

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}