package com.zenred.data_access;

/**
 *  ###  Generated by OracleAS TopLink Mapping Workbench 10g (9.0.4.5) - Fri Apr 15 14:04:11 PDT 2005.  ###
 */

public class Clusterrep {

	private Float angleInRadians;
	private String clusterDescription;
	private String clusterId;
	private Float distanceSysVirtCentre;
	private Double numberStarsInCluster;
	private Character planetsallowed;
	private String systemId;
	private String datestamp;

public Clusterrep() {
	super();
}

public Float getAngleInRadians() {
	return this.angleInRadians;
}

public String getClusterDescription() {
	return this.clusterDescription;
}

public String getClusterId() {
	return this.clusterId;
}

public String getDatestamp() {
	return this.datestamp;
}

public Float getDistanceSysVirtCentre() {
	return this.distanceSysVirtCentre;
}

public Double getNumberStarsInCluster() {
	return this.numberStarsInCluster;
}

public Character getPlanetsallowed() {
	return this.planetsallowed;
}

public String getSystemId() {
	return this.systemId;
}

public void setAngleInRadians(Float angleInRadians) {
	this.angleInRadians = angleInRadians;
}

public void setClusterDescription(String clusterDescription) {
	this.clusterDescription = clusterDescription;
}

public void setClusterId(String clusterId) {
	this.clusterId = clusterId;
}

public void setDatestamp(String datestamp) {
	this.datestamp = datestamp;
}

public void setDistanceSysVirtCentre(Float distanceSysVirtCentre) {
	this.distanceSysVirtCentre = distanceSysVirtCentre;
}

public void setNumberStarsInCluster(Double numberStarsInCluster) {
	this.numberStarsInCluster = numberStarsInCluster;
}

public void setPlanetsallowed(Character planetsallowed) {
	this.planetsallowed = planetsallowed;
}

public void setSystemId(String systemId) {
	this.systemId = systemId;
}

public String toString() {
	// Fill in method body here.
	return null;
}

}
