package com.zenred.data_access;

import java.util.Calendar;

/**
 * ### Generated by OracleAS TopLink Mapping Workbench 10g (9.0.4.5) - Fri Apr
 * 15 14:04:16 PDT 2005. ###
 */

public class Planetoid {

	private Calendar datestamp;
	private Double degree;
	private Double distancetopimary;
	private Double percentwater;
	private String planetoidId;
	private Double radius;
	private Double temperature;

	private Double distance_au;
	private Double period;

	public Double getDistance_au() {
		return distance_au;
	}

	public void setDistance_au(Double distance_au) {
		this.distance_au = distance_au;
	}

	public Double getPeriod() {
		return period;
	}

	public void setPeriod(Double period) {
		this.period = period;
	}

	public Planetoid() {
		super();
	}

	public Calendar getDatestamp() {
		return this.datestamp;
	}

	public Double getDegree() {
		return this.degree;
	}

	public Double getDistancetopimary() {
		return this.distancetopimary;
	}

	public Double getPercentwater() {
		return this.percentwater;
	}

	public String getPlanetoidId() {
		return this.planetoidId;
	}

	public Double getRadius() {
		return this.radius;
	}

	public Double getTemperature() {
		return this.temperature;
	}

	public void setDatestamp(Calendar datestamp) {
		this.datestamp = datestamp;
	}

	public void setDegree(Double degree) {
		this.degree = degree;
	}

	public void setDistancetopimary(Double distancetopimary) {
		this.distancetopimary = distancetopimary;
	}

	public void setPercentwater(Double percentwater) {
		this.percentwater = percentwater;
	}

	public void setPlanetoidId(String planetoidId) {
		this.planetoidId = planetoidId;
	}

	public void setRadius(Double radius) {
		this.radius = radius;
	}

	public void setTemperature(Double temperature) {
		this.temperature = temperature;
	}

	@Override
	public String toString() {
		return "Planetoid [datestamp=" + datestamp + ", degree=" + degree
				+ ", distancetopimary=" + distancetopimary + ", percentwater="
				+ percentwater + ", planetoidId=" + planetoidId + ", radius="
				+ radius + ", temperature=" + temperature + ", distance_au="
				+ distance_au + ", period=" + period + "]";
	}



}
