package com.zenred.data_access;

/**
 *  ###  Generated by OracleAS TopLink Mapping Workbench 10g (9.0.4.5) - Fri Apr 15 14:04:16 PDT 2005.  ###
 */

public class Planetoid_Atmosphere {


	private String planetoidId;
	private String chem_name;
	private Double percentage;
	
	public Double getPercentage() {
		return percentage;
	}
	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}
	public String getPlanetoidId() {
		return planetoidId;
	}
	public void setPlanetoidId(String planetoidId) {
		this.planetoidId = planetoidId;
	}
	public String getChem_name() {
		return chem_name;
	}
	public void setChem_name(String chem_name) {
		this.chem_name = chem_name;
	}



}
