package com.zenred.data_access;

import java.util.Calendar;

/**
 * ### Generated by OracleAS TopLink Mapping Workbench 10g (9.0.4.5) - Fri Apr
 * 15 14:04:16 PDT 2005. ###
 */

public class Planetoidrep implements PlanetoidRepIF {

	private String clusterId;
	private Calendar datestamp;
	private String planetoidId;
	private String profile;
	private String systemId;
	private String itsStar;

	public Planetoidrep() {
		super();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.zenred.data_access.PlanetoidRepIF#getClusterId()
	 */
	public String getClusterId() {
		return this.clusterId;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.zenred.data_access.PlanetoidRepIF#getDatestamp()
	 */
	public Calendar getDatestamp() {
		return this.datestamp;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.zenred.data_access.PlanetoidRepIF#getPlanetoidId()
	 */
	public String getPlanetoidId() {
		return this.planetoidId;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.zenred.data_access.PlanetoidRepIF#getProfile()
	 */
	public String getProfile() {
		return this.profile;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.zenred.data_access.PlanetoidRepIF#getSystemId()
	 */
	public String getSystemId() {
		return this.systemId;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.zenred.data_access.PlanetoidRepIF#setClusterId(java.lang.String)
	 */
	public void setClusterId(String clusterId) {
		this.clusterId = clusterId;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.zenred.data_access.PlanetoidRepIF#setDatestamp(java.util.Calendar)
	 */
	public void setDatestamp(Calendar datestamp) {
		this.datestamp = datestamp;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.zenred.data_access.PlanetoidRepIF#setPlanetoidId(java.lang.String)
	 */
	public void setPlanetoidId(String planetoidId) {
		this.planetoidId = planetoidId;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.zenred.data_access.PlanetoidRepIF#setProfile(java.lang.String)
	 */
	public void setProfile(String profile) {
		this.profile = profile;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.zenred.data_access.PlanetoidRepIF#setSystemId(java.lang.String)
	 */
	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	public String toString() {
		return "Planetoidrep [clusterId=" + clusterId + ", datestamp="
				+ datestamp + ", planetoidId=" + planetoidId + ", profile="
				+ profile + ", systemId=" + systemId + ", itsStar=" + itsStar
				+ "]";
	}

	public String getItsStar() {
		return itsStar;
	}

	public void setItsStar(String itsStar) {
		this.itsStar = itsStar;

	}
	
	

}
