package com.zenred.data_access;

import java.util.Calendar;

/**
 *  ###  Generated by OracleAS TopLink Mapping Workbench 10g (9.0.4.5) - Fri Apr 15 14:04:16 PDT 2005.  ###
 */

public class Planetoidatmosphere {

	private Double ammonia;
	private Double argon;
	private Double carbon;
	private Double carbonDioxide;
	private Double chlorine;
	private Calendar datestamp;
	private Double helium;
	private Double hydrochloric;
	private Double hydrogen;
	private Double methane;
	private Double neon;
	private Double nitrogen;
	private Double nitrogenDioxide;
	private Double oxygen;
	private String planetoidId;
	private Double sulfer;
	private Double sulfuric;
	private Double water;

public Planetoidatmosphere() {
	super();
}

public Double getAmmonia() {
	return this.ammonia;
}

public Double getArgon() {
	return this.argon;
}

public Double getCarbon() {
	return this.carbon;
}

public Double getCarbonDioxide() {
	return this.carbonDioxide;
}

public Double getChlorine() {
	return this.chlorine;
}

public Calendar getDatestamp() {
	return this.datestamp;
}

public Double getHelium() {
	return this.helium;
}

public Double getHydrochloric() {
	return this.hydrochloric;
}

public Double getHydrogen() {
	return this.hydrogen;
}

public Double getMethane() {
	return this.methane;
}

public Double getNeon() {
	return this.neon;
}

public Double getNitrogen() {
	return this.nitrogen;
}

public Double getNitrogenDioxide() {
	return this.nitrogenDioxide;
}

public Double getOxygen() {
	return this.oxygen;
}

public String getPlanetoidId() {
	return this.planetoidId;
}

public Double getSulfer() {
	return this.sulfer;
}

public Double getSulfuric() {
	return this.sulfuric;
}

public Double getWater() {
	return this.water;
}

public void setAmmonia(Double ammonia) {
	this.ammonia = ammonia;
}

public void setArgon(Double argon) {
	this.argon = argon;
}

public void setCarbon(Double carbon) {
	this.carbon = carbon;
}

public void setCarbonDioxide(Double carbonDioxide) {
	this.carbonDioxide = carbonDioxide;
}

public void setChlorine(Double chlorine) {
	this.chlorine = chlorine;
}

public void setDatestamp(Calendar datestamp) {
	this.datestamp = datestamp;
}

public void setHelium(Double helium) {
	this.helium = helium;
}

public void setHydrochloric(Double hydrochloric) {
	this.hydrochloric = hydrochloric;
}

public void setHydrogen(Double hydrogen) {
	this.hydrogen = hydrogen;
}

public void setMethane(Double methane) {
	this.methane = methane;
}

public void setNeon(Double neon) {
	this.neon = neon;
}

public void setNitrogen(Double nitrogen) {
	this.nitrogen = nitrogen;
}

public void setNitrogenDioxide(Double nitrogenDioxide) {
	this.nitrogenDioxide = nitrogenDioxide;
}

public void setOxygen(Double oxygen) {
	this.oxygen = oxygen;
}

public void setPlanetoidId(String planetoidId) {
	this.planetoidId = planetoidId;
}

public void setSulfer(Double sulfer) {
	this.sulfer = sulfer;
}

public void setSulfuric(Double sulfuric) {
	this.sulfuric = sulfuric;
}

public void setWater(Double water) {
	this.water = water;
}

public String toString() {
	// Fill in method body here.
	return null;
}

}
