package com.zenred.data_access;

import java.util.Calendar;

/**
 *  ###  Generated by OracleAS TopLink Mapping Workbench 10g (9.0.4.5) - Fri Apr 15 14:04:16 PDT 2005.  ###
 */

public class Starrep {

	private Float angleInRadiansS;
	private String clusterId;
	private String datestamp;
	private Float distanceClustVirtCentre;
	private Float luminosity;
	private Character noPlanetsAllowed;
	private String starColor;
	private String starType;
	private String systemId;
  private Float starSize;

public Starrep() {
	super();
}

public Float getAngleInRadiansS() {
	return this.angleInRadiansS;
}

public String getClusterId() {
	return this.clusterId;
}

public String getDatestamp() {
	return this.datestamp;
}

public Float getDistanceClustVirtCentre() {
	return this.distanceClustVirtCentre;
}

public Float getLuminosity() {
	return this.luminosity;
}

public Character getNoPlanetsAllowed() {
	return this.noPlanetsAllowed;
}

public String getStarColor() {
	return this.starColor;
}

public String getStarType() {
	return this.starType;
}

public String getSystemId() {
	return this.systemId;
}

public Float getStarSize()
{
  return starSize;
}

public void setAngleInRadiansS(Float angleInRadiansS) {
	this.angleInRadiansS = angleInRadiansS;
}

public void setClusterId(String clusterId) {
	this.clusterId = clusterId;
}

public void setDatestamp(String datestamp) {
	this.datestamp = datestamp;
}

public void setDistanceClustVirtCentre(Float distanceClustVirtCentre) {
	this.distanceClustVirtCentre = distanceClustVirtCentre;
}

public void setLuminosity(Float luminosity) {
	this.luminosity = luminosity;
}

public void setNoPlanetsAllowed(Character noPlanetsAllowed) {
	this.noPlanetsAllowed = noPlanetsAllowed;
}

public void setStarColor(String starColor) {
	this.starColor = starColor;
}

public void setStarType(String starType) {
	this.starType = starType;
}

public void setSystemId(String systemId) {
	this.systemId = systemId;
}

public void setStarSize(Float starSize)
{
  this.starSize = starSize;
}

public String toString() {
	StringBuffer _str_buf = new StringBuffer()
  .append(':').append(systemId)
  .append(':').append(clusterId)
  .append(':').append(starColor)
  .append(':').append(starType)
  .append(':').append(luminosity.toString())
  .append(':').append(distanceClustVirtCentre.toString())
  .append(':').append(angleInRadiansS.toString())
  .append(':').append(noPlanetsAllowed)
  .append(':').append(starSize)
  .append(':').append(super.toString());
	return _str_buf.toString();
}

}
