package com.zenred.data_access;

/**
 *  ###  Generated by OracleAS TopLink Mapping Workbench 10g (9.0.4.5) - Fri Apr 15 14:04:16 PDT 2005.  ###
 */

public class Systemrep {

	private Float distanceToGalaxyCentre;
	private String systemId;
	private Float ucoordinate;
	private Float vcoordinate;
	private String datestamp;

public Systemrep() {
	super();
}

public String getDatestamp() {
	return this.datestamp;
}

public Float getDistanceToGalaxyCentre() {
	return this.distanceToGalaxyCentre;
}

public String getSystemId() {
	return this.systemId;
}

public Float getUcoordinate() {
	return this.ucoordinate;
}

public Float getVcoordinate() {
	return this.vcoordinate;
}

public void setDatestamp(String datestamp) {
	this.datestamp = datestamp;
}

public void setDistanceToGalaxyCentre(Float distanceToGalaxyCentre) {
	this.distanceToGalaxyCentre = distanceToGalaxyCentre;
}

public void setSystemId(String systemId) {
	this.systemId = systemId;
}

public void setUcoordinate(Float ucoordinate) {
	this.ucoordinate = ucoordinate;
}

public void setVcoordinate(Float vcoordinate) {
	this.vcoordinate = vcoordinate;
}

public String toString() {
	StringBuffer _str_buff = new StringBuffer()
  .append(':').append(systemId)
  .append(':').append(ucoordinate.toString())
  .append(':').append(vcoordinate.toString());
	return _str_buff.toString();
}

}
